version: 2

sources:
  - name: ticket_tailor
    database: raw
    tables:
      - name: events
        freshness: # default freshness
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: _sdc_batched_at   
      - name: orders
        freshness: # default freshness
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: _sdc_batched_at        
      - name: issued_tickets
        freshness: # default freshness
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: _sdc_batched_at   