version: 2

sources:
  - name: jaffle_shop
    description: "{{ doc('jaffle_shop') }}"
    database: raw
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _etl_loaded_at

    tables:
      - name: orders
        description: "{{ doc('orders_source') }}"
        freshness: # make this a little less strict
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        columns:
        - name: id
          tests:
            - not_null
            - unique
      - name: customers
        description: "{{ doc('customers_source') }}"
        freshness: null # do not check freshness for this table
        columns:
          - name: id
            tests:
              - not_null
              - unique
  - name: stripe
    database: raw
    tables:
      - name: payment
        freshness: # default freshness
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: _batched_at
 